// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// new_graph
SEXP new_graph(int V);
RcppExport SEXP _graphs_new_graph(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(new_graph(V));
    return rcpp_result_gen;
END_RCPP
}
// from_edge_list
SEXP from_edge_list(DataFrame df, int V);
RcppExport SEXP _graphs_from_edge_list(SEXP dfSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(from_edge_list(df, V));
    return rcpp_result_gen;
END_RCPP
}
// from_adj_list
SEXP from_adj_list(List list);
RcppExport SEXP _graphs_from_adj_list(SEXP listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type list(listSEXP);
    rcpp_result_gen = Rcpp::wrap(from_adj_list(list));
    return rcpp_result_gen;
END_RCPP
}
// from_adj_matrix
SEXP from_adj_matrix(IntegerMatrix matrix);
RcppExport SEXP _graphs_from_adj_matrix(SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type matrix(matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(from_adj_matrix(matrix));
    return rcpp_result_gen;
END_RCPP
}
// as_edge_list
DataFrame as_edge_list(SEXP sexp);
RcppExport SEXP _graphs_as_edge_list(SEXP sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(as_edge_list(sexp));
    return rcpp_result_gen;
END_RCPP
}
// as_adj_list
List as_adj_list(SEXP sexp);
RcppExport SEXP _graphs_as_adj_list(SEXP sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(as_adj_list(sexp));
    return rcpp_result_gen;
END_RCPP
}
// as_adj_matrix
NumericMatrix as_adj_matrix(SEXP sexp);
RcppExport SEXP _graphs_as_adj_matrix(SEXP sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(as_adj_matrix(sexp));
    return rcpp_result_gen;
END_RCPP
}
// new_graph_dw
SEXP new_graph_dw(IntegerVector num_vertices);
RcppExport SEXP _graphs_new_graph_dw(SEXP num_verticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type num_vertices(num_verticesSEXP);
    rcpp_result_gen = Rcpp::wrap(new_graph_dw(num_vertices));
    return rcpp_result_gen;
END_RCPP
}
// from_adj_list_dw
SEXP from_adj_list_dw(List list);
RcppExport SEXP _graphs_from_adj_list_dw(SEXP listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type list(listSEXP);
    rcpp_result_gen = Rcpp::wrap(from_adj_list_dw(list));
    return rcpp_result_gen;
END_RCPP
}
// from_edge_list_dw
SEXP from_edge_list_dw(DataFrame df, IntegerVector num_vertices);
RcppExport SEXP _graphs_from_edge_list_dw(SEXP dfSEXP, SEXP num_verticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num_vertices(num_verticesSEXP);
    rcpp_result_gen = Rcpp::wrap(from_edge_list_dw(df, num_vertices));
    return rcpp_result_gen;
END_RCPP
}
// from_adj_matrix_dw
SEXP from_adj_matrix_dw(NumericMatrix matrix);
RcppExport SEXP _graphs_from_adj_matrix_dw(SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(from_adj_matrix_dw(matrix));
    return rcpp_result_gen;
END_RCPP
}
// add_edges_dw
void add_edges_dw(SEXP sexp, IntegerVector from, IntegerVector to, NumericVector weights);
RcppExport SEXP _graphs_add_edges_dw(SEXP sexpSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    add_edges_dw(sexp, from, to, weights);
    return R_NilValue;
END_RCPP
}
// as_adj_list_dw
List as_adj_list_dw(SEXP sexp);
RcppExport SEXP _graphs_as_adj_list_dw(SEXP sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(as_adj_list_dw(sexp));
    return rcpp_result_gen;
END_RCPP
}
// as_edge_list_dw
DataFrame as_edge_list_dw(SEXP sexp);
RcppExport SEXP _graphs_as_edge_list_dw(SEXP sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(as_edge_list_dw(sexp));
    return rcpp_result_gen;
END_RCPP
}
// as_adj_matrix_dw
NumericMatrix as_adj_matrix_dw(SEXP sexp);
RcppExport SEXP _graphs_as_adj_matrix_dw(SEXP sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(as_adj_matrix_dw(sexp));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_triangle_count_brute
int rcpp_triangle_count_brute(SEXP sexp);
RcppExport SEXP _graphs_rcpp_triangle_count_brute(SEXP sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp(sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_triangle_count_brute(sexp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graphs_new_graph", (DL_FUNC) &_graphs_new_graph, 1},
    {"_graphs_from_edge_list", (DL_FUNC) &_graphs_from_edge_list, 2},
    {"_graphs_from_adj_list", (DL_FUNC) &_graphs_from_adj_list, 1},
    {"_graphs_from_adj_matrix", (DL_FUNC) &_graphs_from_adj_matrix, 1},
    {"_graphs_as_edge_list", (DL_FUNC) &_graphs_as_edge_list, 1},
    {"_graphs_as_adj_list", (DL_FUNC) &_graphs_as_adj_list, 1},
    {"_graphs_as_adj_matrix", (DL_FUNC) &_graphs_as_adj_matrix, 1},
    {"_graphs_new_graph_dw", (DL_FUNC) &_graphs_new_graph_dw, 1},
    {"_graphs_from_adj_list_dw", (DL_FUNC) &_graphs_from_adj_list_dw, 1},
    {"_graphs_from_edge_list_dw", (DL_FUNC) &_graphs_from_edge_list_dw, 2},
    {"_graphs_from_adj_matrix_dw", (DL_FUNC) &_graphs_from_adj_matrix_dw, 1},
    {"_graphs_add_edges_dw", (DL_FUNC) &_graphs_add_edges_dw, 4},
    {"_graphs_as_adj_list_dw", (DL_FUNC) &_graphs_as_adj_list_dw, 1},
    {"_graphs_as_edge_list_dw", (DL_FUNC) &_graphs_as_edge_list_dw, 1},
    {"_graphs_as_adj_matrix_dw", (DL_FUNC) &_graphs_as_adj_matrix_dw, 1},
    {"_graphs_rcpp_triangle_count_brute", (DL_FUNC) &_graphs_rcpp_triangle_count_brute, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_graphs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
