# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates an undirected, unweighted graph with the provided number of vertices.
#'
#' @param V Number of vertices, must be an integer vector of length 1.
#' @returns Graph object with the provided number of vertices and no edges.
new_graph <- function(V) {
    .Call(`_graphs_new_graph`, V)
}

#' Creates an undirected, unweighted graph from an edgelist.
#'
#' @param df Edgelist dataframe, must have two columns: "from" and "to", representing the two vertices of each edge.
#' Duplicated edges are silently ignored. Indexes outside of range (or NA) throw an error.
#' @param V Number of vertices, must be an integer vector of length 1.
#' @returns Graph constructed from the edgelist.
from_edge_list <- function(df, V) {
    .Call(`_graphs_from_edge_list`, df, V)
}

#' Creates an undirected, unweighted graph from an adjacency list.
#'
#' @param list Adjacency list, represented as a list of integer vectors;
#' k-th vector in the list represents the set of neighbors of vertex k.
#' Neighbors might be in any order, edges can be specified from any one direction or both,
#' duplicated edges will be silently ignored, leaving only a single one.
#' Indexes outside of range (or NA) throw an error.
#' @returns Graph constructed from the adjacency list.
from_adj_list <- function(list) {
    .Call(`_graphs_from_adj_list`, list)
}

#' Creates an undirected, unweighted graph from an adjacency matrix.
#'
#' @param matrix Adjacency matrix. A nonzero element at position (i, j) represent an edge between vertices (i, j).
#' Must be square obviously, and symmetric. NA elements will throw an error.
#' @returns Graph constructed from the adjacency matrix.
from_adj_matrix <- function(matrix) {
    .Call(`_graphs_from_adj_matrix`, matrix)
}

as_edge_list <- function(sexp) {
    .Call(`_graphs_as_edge_list`, sexp)
}

as_adj_list <- function(sexp) {
    .Call(`_graphs_as_adj_list`, sexp)
}

as_adj_matrix <- function(sexp) {
    .Call(`_graphs_as_adj_matrix`, sexp)
}

#' Counts triangles (cycles of length 3) in an undirected, unweighted graph
#'
#' @param sexp The graph object, created using `new_graph` or any of the `from_*` functions
#' @param method The algorithm used to count triangles \itemize{
#' \item brute - for each edge (u, v) count how many neighbors of u are also neighbors of v, O(E * V * log(V))
#' \item intersect - for each edge (u, v) count the size of the intersection of their sets of neighbors, O(E * V)
#' }
#' @returns Number of unique triangles (cycles of length 3) in the graph
triangle_count <- function(sexp, method) {
    .Call(`_graphs_triangle_count`, sexp, method)
}

