# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates an undirected, unweighted graph with the provided number of vertices.
#'
#' @param V Number of vertices, must be an integer vector of length 1.
#' @returns Graph object with the provided number of vertices and no edges.
new_graph <- function(V) {
    .Call(`_graphs_new_graph`, V)
}

#' Creates an undirected, unweighted graph from an edgelist.
#'
#' @param df Edgelist dataframe, must have two columns: "from" and "to", representing the two vertices of each edge.
#' Duplicated edges are silently ignored. Indexes outside of range (or NA) throw an error.
#' @param V Number of vertices, must be an integer vector of length 1.
#' @returns Graph constructed from the edgelist.
from_edge_list <- function(df, V) {
    .Call(`_graphs_from_edge_list`, df, V)
}

#' Creates an undirected, unweighted graph from an adjacency list.
#'
#' @param list Adjacency list, represented as a list of integer vectors;
#' k-th vector in the list represents the set of neighbors of vertex k.
#' Neighbors might be in any order, edges can be specified from any one direction or both,
#' duplicated edges will be silently ignored, leaving only a single one.
#' Indexes outside of range (or NA) throw an error.
#' @returns Graph constructed from the adjacency list.
from_adj_list <- function(list) {
    .Call(`_graphs_from_adj_list`, list)
}

#' Creates an undirected, unweighted graph from an adjacency matrix.
#'
#' @param matrix Adjacency matrix. A nonzero element at position (i, j) represent an edge between vertices (i, j).
#' Must be square obviously, and symmetric. NA elements will throw an error.
#' @returns Graph constructed from the adjacency matrix.
from_adj_matrix <- function(matrix) {
    .Call(`_graphs_from_adj_matrix`, matrix)
}

#' Exports graph as edgelist.
#'
#' @param sexp Graph object.
#' @returns Edgelist - data frame with two columns: "from" and "to",
#' representing two endpoints of every edge.
#' Every edge (u, v) is only included once, in order u < v.
#' The ordering of edges is guaranteed to be deterministic,
#' and will be the same for every created graph object with the same set of vertices and edges.
#' Also, in the current implementation edges are sorted first by v and then by u,
#' but this specific ordering definitely shouldn't be relied upon and might change in the future.
as_edge_list <- function(sexp) {
    .Call(`_graphs_as_edge_list`, sexp)
}

#' Exports graph as an adjacency list.
#'
#' @param sexp Graph object.
#' @returns Adjacency list - a list of integer vectors, where k-th vector represents neighbors of vertex k.
#' Every edge (u, v) will be included in both directions,
#' i.e. u will be included as neighbor of v, and v as neighbor of u.
#' The ordering of neighbors is guaranteed to be deterministic,
#' and will be the same for every created graph object with the same set of vertices and edges.
#' Also, in the current implementation neighbors of every vertex are sorted in increasing order.
#' This probably won't change, but isn't guaranteed, so shouldn't be relied upon too much.
as_adj_list <- function(sexp) {
    .Call(`_graphs_as_adj_list`, sexp)
}

#' Exports graph as an adjacency matrix.
#' @param sexp Graph object.
#' @returns Adjacency matrix - a numeric matrix of size (V, V),
#' where V is the number of vertices. Element (i, j) will be set to 1
#' if there's an edge between vertices i, j and 0 if there isn't.
#' The matrix is of course square and symmetric.
as_adj_matrix <- function(sexp) {
    .Call(`_graphs_as_adj_matrix`, sexp)
}

#' Add edge to graph
#' @description Adds an edge between vertices (u, v) if it doesn't already exist in the graph.
#' @param sexp Graph object.
#' @param u, v Vertices between which an edge will be added. Must be valid vertices in the graph, and not NA.
#' @returns TRUE if the edge has been added, FALSE if it already existed and hasn't been added.
add_edge <- function(sexp, u, v) {
    .Call(`_graphs_add_edge`, sexp, u, v)
}

#' Remove edge from graph
#' @description Removes an edge between vertices (u, v) if it exists in the graph.
#' @param sexp Graph object.
#' @param u, v Vertices connected by the edge which will be removed. Must be valid vertices in the graph, and not NA.
#' @returns TRUE if the edge has been removed, FALSE if it didn't exist and so couldn't be removed.
remove_edge <- function(sexp, u, v) {
    .Call(`_graphs_remove_edge`, sexp, u, v)
}

#' Counts triangles (cycles of length 3) in an undirected, unweighted graph
#'
#' @param sexp The graph object, created using `new_graph` or any of the `from_*` functions
#' @param method The algorithm used to count triangles: \itemize{
#' \item brute - for each edge (u, v) count how many neighbors of u are also neighbors of v, O(E * V * log(V))
#' \item intersect - for each edge (u, v) count the size of the intersection of their sets of neighbors, O(E * V)
#' }
#' @returns Number of unique triangles (cycles of length 3) in the graph
triangle_count <- function(sexp, method) {
    .Call(`_graphs_triangle_count`, sexp, method)
}

#' Enable/disable online triangle counting
#' @description Enables or disables optimized online triangle counting for the provided graph object.
#' When enabled, computes initial triangle count using an offline algorithm (the same as triangle_count(method = "intersect")).
#' Enabling when already enabled or disabling when already disabled does nothing.
#' @param sexp Graph object.
#' @param enable Whether to enable (TRUE) or disable (FALSE) online triangle counting.
enable_triangle_count <- function(sexp, enable = TRUE) {
    invisible(.Call(`_graphs_enable_triangle_count`, sexp, enable))
}

